Repository iterative/helm-charts, pull requests merged in 2023-06, with the labels that each got.

#102 fix(migrations): Move django migration to init-containers and fix phonenumber migration
  charts/studio/Chart.yaml
  charts/studio/templates/deployment-studio-backend.yaml
  charts/studio/templates/deployment-studio-ui.yaml
Labels: bug, p0-critical

#104 Fix(values): Restore storageClassName value in blobvault
  charts/studio/Chart.yaml
  charts/studio/values.yaml
Labels: bug

#108 Configure Postgres with separate env variables
  charts/studio/Chart.yaml
  charts/studio/templates/secret-studio.yaml
  charts/studio/values.yaml
Labels: enhancement

#109 Bump app version to v2.9.1
  charts/studio/Chart.yaml
Labels: bug
