Repository iterative/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#16 Add support to define CA certificates
  charts/studio/templates/configmap.yaml
  charts/studio/templates/deployment-studio-backend.yaml
  charts/studio/templates/deployment-studio-beat.yaml
  charts/studio/templates/deployment-studio-ui.yaml
  charts/studio/templates/deployment-studio-worker.yaml
  charts/studio/values.yaml
Labels: enhancement

#26 Add release notes template
  .github/release.yml
Labels: documentation

#28 Refactor values.yaml, document each variable
  README.md
  charts/studio/templates/_env_vars.tpl
  charts/studio/templates/secrets.yaml
  charts/studio/values.yaml
Labels: breaking-change

#31 Update installation instructions to use Helm repository
  README.md
Labels: documentation

#37 Dynamically generate SCM_PROVIDERS
  charts/studio/templates/_env_vars.tpl
Labels: bug

#32 Set default Helm namespace to Studio
  README.md
  charts/studio/Chart.yaml
Labels: documentation

#39 README: Fix secret, create namespace
  .gitignore
  README.md
Labels: documentation

#48 Include GITHUB_API_URL in env vars template
  charts/studio/templates/_env_vars.tpl
Labels: bug

#49 Remove hosts and TLS ranges in Ingress resources
  charts/studio/templates/NOTES.txt
  charts/studio/templates/_env_vars.tpl
  charts/studio/templates/ingress-backend.yaml
  charts/studio/templates/ingress-ui.yaml
  charts/studio/values.yaml
Labels: breaking-change

#51 Fix SCM_PROVIDERS generation
  charts/studio/templates/_env_vars.tpl
  charts/studio/values.yaml
Labels: breaking-change

#53 Fix conditionals templates
  charts/studio/Chart.yaml
  charts/studio/templates/NOTES.txt
  charts/studio/templates/ingress-backend.yaml
  charts/studio/templates/ingress-ui.yaml
Labels: bug

#54 Add enableWebhookSSL setting
  charts/studio/Chart.yaml
  charts/studio/templates/_env_vars.tpl
  charts/studio/values.yaml
Labels: enhancement

#55 Fix pathType in ingress-ui
  charts/studio/Chart.yaml
  charts/studio/templates/ingress-ui.yaml
Labels: bug

#59 fix: Conditionally pass SCM provider env variables
  charts/studio/templates/configmap-studio.yaml
  charts/studio/values.yaml
Labels: bug

#58 bug: Fix how GitHub private key is beeing rendered in secret.
  charts/studio/Chart.yaml
  charts/studio/templates/secret-studio.yaml
Labels: bug

#61 fix: templates typo fix
  charts/studio/templates/configmap-studio.yaml
Labels: bug

#63 Assortment of fixes
  README.md
  charts/studio/Chart.yaml
  charts/studio/templates/NOTES.txt
  charts/studio/templates/configmap-studio.yaml
  charts/studio/templates/deployment-studio-backend.yaml
  charts/studio/templates/ingress-studio.yaml
  charts/studio/templates/secret-studio.yaml
  charts/studio/values.yaml
Labels: bug

#65 Remove trailing slash in SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS
  charts/studio/templates/configmap-studio.yaml
Labels: bug

#68 Add variable for secure flag on session cookies
  charts/studio/Chart.yaml
  charts/studio/templates/configmap-studio.yaml
  charts/studio/values.yaml
Labels: bug
